finish TODOs from template
This gets the plugin working with some recent versions.

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -10,14 +10,14 @@ source "${plugin_dir}/lib/utils.bash"
 
 mkdir -p "$ASDF_DOWNLOAD_PATH"
 
-# TODO: Adapt this to proper extension and adapt extracting strategy.
-release_file="$ASDF_DOWNLOAD_PATH/$TOOL_NAME-$ASDF_INSTALL_VERSION.tar.gz"
-
-# Download tar.gz file to the download directory
+release_file="$ASDF_DOWNLOAD_PATH/$(basename "$(get_download_url "$ASDF_INSTALL_VERSION")")"
+extension="${release_file##*.}"
 download_release "$ASDF_INSTALL_VERSION" "$release_file"
 
-#  Extract contents of tar.gz file into the download directory
-tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
-
-# Remove the tar.gz file since we don't need to keep it
-rm "$release_file"
+if [[ "$extension" == "zip" ]]; then
+  (unzip "$ASDF_DOWNLOAD_PATH/$release_file" && f=(./*) && mv ./*/* . && rmdir "${f[@]}") || fail "Could not extract $release_file"
+  rm "$release_file"
+else
+  tar -xf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 || fail "Could not extract $release_file"
+  rm "$release_file"
+fi
